# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x06\x63lient\"?\n\x0bTickerPrice\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"<\n\x0fPutPriceRequest\x12)\n\x0cticker_price\x18\x01 \x01(\x0b\x32\x13.client.TickerPrice\"J\n\x10PutPriceResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0bleader_hint\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"B\n\x14\x42\x61tchPutPriceRequest\x12*\n\rticker_prices\x18\x01 \x03(\x0b\x32\x13.client.TickerPrice\"O\n\x15\x42\x61tchPutPriceResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0bleader_hint\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"!\n\x0fGetPriceRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"c\n\x10GetPriceResponse\x12)\n\x0cticker_price\x18\x01 \x01(\x0b\x32\x13.client.TickerPrice\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x17\n\x15GetClusterInfoRequest\"i\n\x16GetClusterInfoResponse\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x04\x12\x0f\n\x07members\x18\x03 \x03(\t\x12\x0f\n\x07node_id\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t2\xac\x02\n\rClientService\x12=\n\x08PutPrice\x12\x17.client.PutPriceRequest\x1a\x18.client.PutPriceResponse\x12L\n\rBatchPutPrice\x12\x1c.client.BatchPutPriceRequest\x1a\x1d.client.BatchPutPriceResponse\x12=\n\x08GetPrice\x12\x17.client.GetPriceRequest\x1a\x18.client.GetPriceResponse\x12O\n\x0eGetClusterInfo\x12\x1d.client.GetClusterInfoRequest\x1a\x1e.client.GetClusterInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKERPRICE']._serialized_start=24
  _globals['_TICKERPRICE']._serialized_end=87
  _globals['_PUTPRICEREQUEST']._serialized_start=89
  _globals['_PUTPRICEREQUEST']._serialized_end=149
  _globals['_PUTPRICERESPONSE']._serialized_start=151
  _globals['_PUTPRICERESPONSE']._serialized_end=225
  _globals['_BATCHPUTPRICEREQUEST']._serialized_start=227
  _globals['_BATCHPUTPRICEREQUEST']._serialized_end=293
  _globals['_BATCHPUTPRICERESPONSE']._serialized_start=295
  _globals['_BATCHPUTPRICERESPONSE']._serialized_end=374
  _globals['_GETPRICEREQUEST']._serialized_start=376
  _globals['_GETPRICEREQUEST']._serialized_end=409
  _globals['_GETPRICERESPONSE']._serialized_start=411
  _globals['_GETPRICERESPONSE']._serialized_end=510
  _globals['_GETCLUSTERINFOREQUEST']._serialized_start=512
  _globals['_GETCLUSTERINFOREQUEST']._serialized_end=535
  _globals['_GETCLUSTERINFORESPONSE']._serialized_start=537
  _globals['_GETCLUSTERINFORESPONSE']._serialized_end=642
  _globals['_CLIENTSERVICE']._serialized_start=645
  _globals['_CLIENTSERVICE']._serialized_end=945
# @@protoc_insertion_point(module_scope)
