#!/usr/bin/env python3
"""
Guided, narrated walk through several Raft failure/recovery scenarios
against the live 15-node cluster, paced so each event is visible on the
"Cluster Health" Grafana dashboard (http://localhost:3000/d/raft-cluster-health)
as it happens.

Unlike chaos_test.py (fast, automated pass/fail assertions, no pauses),
this script is for watching: it prints what's about to happen, does it,
and sleeps long enough for the dashboard's 5s refresh to pick it up before
moving on. Run it with the cluster, Prometheus, and Grafana already up
(see README.md's "Running the Cluster" / "Monitoring & Alerting" sections).

Usage:
    PYTHONPATH=. python3 scripts/dashboard_demo.py
    PYTHONPATH=. python3 scripts/dashboard_demo.py --scenario quorum-loss
"""

import asyncio
import argparse
import subprocess
import sys
import time
from typing import Dict, List, Optional

import aiohttp

sys.path.insert(0, '.')
from scripts.kvctl import RaftClient

PROMETHEUS_URL = "http://localhost:9090"
GRAFANA_URL = "http://localhost:3000"
GRAFANA_AUTH = aiohttp.BasicAuth("admin", "admin")

# Matches ops/docker-compose.yml as generated by scripts/gen_docker_compose.py:
# node N's client port is 51050+N, docker-compose service name is "nodeN".
CLUSTER_NODES = {f"node{i}": f"localhost:{51050 + i}" for i in range(1, 16)}


def narrate(title: str, watch: str = "") -> None:
    print()
    print("=" * 70)
    print(title)
    if watch:
        print(f"  Watch: {watch}")
    print("=" * 70)


async def prom_query(session: aiohttp.ClientSession, query: str) -> List[dict]:
    async with session.get(f"{PROMETHEUS_URL}/api/v1/query", params={"query": query}) as resp:
        data = await resp.json()
        return data.get("data", {}).get("result", [])


async def get_leader(session: aiohttp.ClientSession) -> Optional[str]:
    result = await prom_query(session, "raft_node_role==2")
    if not result:
        return None
    return result[0]["metric"]["node_id"]


async def get_terms(session: aiohttp.ClientSession) -> Dict[str, str]:
    result = await prom_query(session, "raft_current_term")
    return {r["metric"]["node_id"]: r["value"][1] for r in result}


async def get_targets_up(session: aiohttp.ClientSession) -> int:
    result = await prom_query(session, 'up{job="raft-nodes"}')
    return sum(1 for r in result if r["value"][1] == "1")


async def get_alert_state(session: aiohttp.ClientSession, alert_name: str) -> str:
    """Returns the alert's current state (e.g. 'Normal', 'Alerting', 'Pending')
    by name, via Grafana's alertmanager-compatible API. Returns 'Normal' if
    the alert isn't in the active list at all (i.e. not currently firing)."""
    url = f"{GRAFANA_URL}/api/alertmanager/grafana/api/v2/alerts"
    async with session.get(url, auth=GRAFANA_AUTH) as resp:
        alerts = await resp.json()
        if resp.status != 200 or not isinstance(alerts, list):
            return f"unknown (HTTP {resp.status}: {alerts})"
    for a in alerts:
        if a.get("labels", {}).get("alertname") == alert_name:
            return a.get("status", {}).get("state", "unknown")
    return "Normal"


async def stop_node(node_id: str) -> None:
    print(f"  -> docker compose stop {node_id}")
    await asyncio.to_thread(
        subprocess.run,
        ['docker', 'compose', '-f', 'ops/docker-compose.yml', 'stop', node_id],
        check=True, capture_output=True
    )


async def start_node(node_id: str) -> None:
    print(f"  -> docker compose start {node_id}")
    await asyncio.to_thread(
        subprocess.run,
        ['docker', 'compose', '-f', 'ops/docker-compose.yml', 'start', node_id],
        check=True, capture_output=True
    )
    await asyncio.sleep(5)


async def wait_for_leader_change(session: aiohttp.ClientSession, old_leader: Optional[str],
                                  timeout: float = 20.0) -> Optional[str]:
    """Poll until a leader different from old_leader appears, or timeout."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        leader = await get_leader(session)
        if leader and leader != old_leader:
            return leader
        await asyncio.sleep(1)
    return None


async def print_cluster_snapshot(session: aiohttp.ClientSession, label: str) -> None:
    up = await get_targets_up(session)
    leader = await get_leader(session)
    terms = await get_terms(session)
    distinct_terms = set(terms.values())
    print(f"[{label}] targets up: {up}/15, leader: {leader}, "
          f"terms: {distinct_terms if len(distinct_terms) > 1 else terms.get(leader, '?')}")


async def scenario_baseline(session: aiohttp.ClientSession) -> None:
    narrate("SCENARIO 0: Baseline health check")
    await print_cluster_snapshot(session, "baseline")


async def scenario_write_burst(session: aiohttp.ClientSession) -> None:
    narrate(
        "SCENARIO 1: Write burst",
        watch="Per-Follower Commit Lag panel — commit_index should climb across all nodes"
    )
    leader = await get_leader(session)
    if not leader:
        print("  No leader found, skipping.")
        return
    host, port = CLUSTER_NODES[leader].split(':')
    client = RaftClient(host, int(port))
    print(f"  Writing 10 prices through leader {leader}...")
    for i in range(10):
        await client.put_price(f"DEMO{i}", 100.0 + i, int(time.time() * 1000))
        await asyncio.sleep(0.5)
    await client.close()
    await print_cluster_snapshot(session, "after write burst")


async def scenario_leader_failover(session: aiohttp.ClientSession) -> None:
    narrate(
        "SCENARIO 2: Leader failover",
        watch="Current Role panel flips, Current Term jumps, Leader Changes Over Time spikes"
    )
    old_leader = await get_leader(session)
    if not old_leader:
        print("  No leader found, skipping.")
        return
    print(f"  Current leader: {old_leader}. Stopping it...")
    await stop_node(old_leader)

    new_leader = await wait_for_leader_change(session, old_leader)
    if new_leader:
        print(f"  New leader elected: {new_leader}")
    else:
        print("  WARNING: no new leader observed within timeout")

    print(f"  Restarting {old_leader}...")
    await start_node(old_leader)
    await print_cluster_snapshot(session, "after failover + rejoin")


async def scenario_follower_catchup(session: aiohttp.ClientSession) -> None:
    narrate(
        "SCENARIO 3: Follower catch-up",
        watch="Per-Follower Commit Lag panel — one node should spike above 0, then drop back to 0"
    )
    leader = await get_leader(session)
    follower = next((n for n in CLUSTER_NODES if n != leader), None)
    if not leader or not follower:
        print("  Could not identify leader/follower, skipping.")
        return

    print(f"  Stopping follower {follower} (leader {leader} stays up)...")
    await stop_node(follower)

    host, port = CLUSTER_NODES[leader].split(':')
    client = RaftClient(host, int(port))
    print("  Writing 5 more prices while the follower is down...")
    for i in range(5):
        await client.put_price(f"CATCHUP{i}", 200.0 + i, int(time.time() * 1000))
        await asyncio.sleep(0.5)
    await client.close()

    print(f"  Restarting {follower} - it should catch up via heartbeat piggybacking...")
    await start_node(follower)
    await asyncio.sleep(3)
    await print_cluster_snapshot(session, "after follower catch-up")


async def scenario_quorum_loss(session: aiohttp.ClientSession) -> None:
    narrate(
        "SCENARIO 4: Quorum loss (triggers the 'No leader elected' alert)",
        watch="Quorum Health panel drops below 8, Grafana Alerting page shows 'No leader elected' -> Alerting"
    )
    # Stop 8 of 15 nodes - breaks the majority needed to elect/hold a leader.
    # Must include the CURRENT leader: Raft has no built-in lease/step-down-
    # on-isolation mechanism, so a leader that's still up but cut off from
    # the majority keeps reporting role=leader indefinitely (it just can't
    # commit anything) - the "no leader" alert would never fire if the old
    # leader happened to land in the surviving minority.
    current_leader = await get_leader(session)
    candidates = [n for n in CLUSTER_NODES if n != current_leader]
    to_stop = ([current_leader] if current_leader else []) + candidates[:7]
    to_stop = to_stop[:8]
    print(f"  Stopping {len(to_stop)} nodes (including current leader {current_leader}) to break quorum: {to_stop}")
    for node_id in to_stop:
        await stop_node(node_id)

    print("  Holding quorum-broken state for 25s (alert needs 10s sustained + evaluation lag)...")
    for remaining in (25, 15, 5):
        await asyncio.sleep(10 if remaining == 25 else 10 if remaining == 15 else 5)
        state = await get_alert_state(session, "No leader elected")
        print(f"  [{remaining}s mark] 'No leader elected' alert state: {state}")

    print("  Restoring quorum...")
    for node_id in to_stop:
        await start_node(node_id)

    print("  Waiting for alert to resolve...")
    await asyncio.sleep(15)
    state = await get_alert_state(session, "No leader elected")
    print(f"  'No leader elected' alert state after recovery: {state}")
    await print_cluster_snapshot(session, "after quorum loss + recovery")


async def scenario_leader_flapping(session: aiohttp.ClientSession) -> None:
    narrate(
        "SCENARIO 5: Leader flapping (triggers the 'Leader changing too frequently' alert)",
        watch="Leader Changes Over Time panel spikes repeatedly, Grafana Alerting page shows "
              "'Leader changing too frequently' -> Alerting"
    )
    for i in range(3):
        leader = await get_leader(session)
        if not leader:
            print(f"  [{i+1}/3] No leader found, waiting...")
            await asyncio.sleep(3)
            continue
        print(f"  [{i+1}/3] Restarting current leader {leader}...")
        await stop_node(leader)
        await wait_for_leader_change(session, leader, timeout=15)
        await start_node(leader)
        await asyncio.sleep(2)

    print("  Checking flapping alert state...")
    await asyncio.sleep(10)
    state = await get_alert_state(session, "Leader changing too frequently")
    print(f"  'Leader changing too frequently' alert state: {state}")

    print("  Waiting 60s for the flapping window to age out and the alert to resolve...")
    await asyncio.sleep(60)
    state = await get_alert_state(session, "Leader changing too frequently")
    print(f"  'Leader changing too frequently' alert state after cooldown: {state}")
    await print_cluster_snapshot(session, "after flapping test")


async def scenario_final_check(session: aiohttp.ClientSession) -> None:
    narrate("SCENARIO 6: Final health check")
    up = await get_targets_up(session)
    leader = await get_leader(session)
    terms = await get_terms(session)
    distinct_terms = set(terms.values())
    healthy = up == 15 and leader is not None and len(distinct_terms) == 1
    print(f"  Targets up: {up}/15")
    print(f"  Leader: {leader}")
    print(f"  Terms converged: {distinct_terms}")
    print(f"  CLUSTER {'HEALTHY' if healthy else 'NOT FULLY HEALTHY - check manually'}")


SCENARIOS = {
    "baseline": scenario_baseline,
    "write-burst": scenario_write_burst,
    "leader-failover": scenario_leader_failover,
    "follower-catchup": scenario_follower_catchup,
    "quorum-loss": scenario_quorum_loss,
    "leader-flapping": scenario_leader_flapping,
    "final-check": scenario_final_check,
}


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--scenario", choices=list(SCENARIOS.keys()) + ["all"], default="all",
        help="Run a single scenario, or 'all' (default) to run the full sequence."
    )
    args = parser.parse_args()

    async with aiohttp.ClientSession() as session:
        if args.scenario == "all":
            print("Running the full demo sequence. Open http://localhost:3000/d/raft-cluster-health "
                  "and the Grafana Alerting page now.")
            for name, fn in SCENARIOS.items():
                await fn(session)
        else:
            await SCENARIOS[args.scenario](session)


if __name__ == "__main__":
    asyncio.run(main())
